// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/views/exception/403.vue')['default']
    404: typeof import('./../src/views/exception/404.vue')['default']
    500: typeof import('./../src/views/exception/500.vue')['default']
    About: typeof import('./../src/views/about/index.vue')['default']
    BasicLayout: typeof import('./../src/layout/BasicLayout/index.vue')['default']
    BlankLayout: typeof import('./../src/layout/BlankLayout/index.vue')['default']
    CarbonClose: typeof import('./../src/components/Icon/CarbonClose.vue')['default']
    CarbonSettings: typeof import('./../src/components/Icon/CarbonSettings.vue')['default']
    ContentLayout: typeof import('./../src/layout/components/content-layout/index.vue')['default']
    Coordinate: typeof import('./../src/views/login/cpns/coordinate.vue')['default']
    DrawerButton: typeof import('./../src/layout/components/theme-setting/drawer-button/index.vue')['default']
    DrawerContent: typeof import('./../src/layout/components/theme-setting/drawer-content/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ExceptionBase: typeof import('./../src/components/Exception/ExceptionBase.vue')['default']
    GlobalConfig: typeof import('./../src/layout/components/theme-setting/drawer-content/global-config/index.vue')['default']
    GlobalLayout: typeof import('./../src/layout/components/theme-setting/drawer-content/global-layout/index.vue')['default']
    GlobalTheme: typeof import('./../src/layout/components/theme-setting/drawer-content/global-theme/index.vue')['default']
    IconCustomSign: typeof import('~icons/custom/sign')['default']
    Login: typeof import('./../src/views/login/index.vue')['default']
    LoginAccount: typeof import('./../src/views/login/cpns/login-account.vue')['default']
    LoginPreview: typeof import('./../src/views/login/cpns/login-preview.vue')['default']
    LogosBitriseIcon: typeof import('./../src/components/Icon/LogosBitriseIcon.vue')['default']
    Redirect: typeof import('./../src/views/redirect/index.vue')['default']
    SettingMenu: typeof import('./../src/components/SettingMenu/index.vue')['default']
    ThemeSetting: typeof import('./../src/layout/components/theme-setting/index.vue')['default']
  }
}

export {}
