// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/views/exception/403.vue')['default']
    404: typeof import('./../src/views/exception/404.vue')['default']
    500: typeof import('./../src/views/exception/500.vue')['default']
    About: typeof import('./../src/views/about/index.vue')['default']
    BasicLayout: typeof import('./../src/layout/BasicLayout/index.vue')['default']
    BlankLayout: typeof import('./../src/layout/BlankLayout/index.vue')['default']
    ContentLayout: typeof import('./../src/layout/components/content-layout/index.vue')['default']
    Coordinate: typeof import('./../src/views/login/cpns/coordinate.vue')['default']
    ExceptionBase: typeof import('./../src/components/exception/ExceptionBase.vue')['default']
    IconCustomSign: typeof import('~icons/custom/sign')['default']
    Login: typeof import('./../src/views/login/index.vue')['default']
    LoginAccount: typeof import('./../src/views/login/cpns/login-account.vue')['default']
    LoginPreview: typeof import('./../src/views/login/cpns/login-preview.vue')['default']
    Redirect: typeof import('./../src/views/redirect/index.vue')['default']
  }
}

export { }
